[[headers]]
  for = "/planet/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/static/media/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/static/media/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
